export const ADD_TASK = "ADD_TASK";
export const REMOVE_TASK = "REMOVE_TASK";
export const MARK_COMPLETED = "MARK_COMPLETED";
export const UPDATE_TASK = "UPDATE_TASK";
export const UPDATE_PERCENTAGE = "UPDATE_PERCENTAGE";